# Generated by Django 3.0.7 on 2020-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/one.png', null=True, upload_to='', verbose_name='تصویر محصول'),
        ),
    ]
