# Generated by Django 3.0.7 on 2020-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blogs', models.ManyToManyField(blank=True, to='eshop_blog.Blog')),
            ],
        ),
    ]
