# Generated by Django 3.0.7 on 2020-06-28 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userBlog', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='no this is little'), django.core.validators.MaxLengthValidator(limit_value=20, message='no this is big')], verbose_name='نام کاربر تولیدکننده ی محتوا')),
                ('titleBlog', models.CharField(max_length=120, verbose_name='عنوان خبر')),
                ('descriptionBlog', models.TextField(verbose_name='متن خبر')),
                ('imageBlog', models.ImageField(upload_to='', verbose_name='تصویر خبر')),
                ('activeBlog', models.BooleanField(default=False, verbose_name='نمایش/روح')),
                ('timeBlog', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
