# Generated by Django 3.0.7 on 2020-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0001_initial'),
        ('eshop_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='eshop_products.Product', verbose_name='محصولات'),
        ),
    ]
