# Generated by Django 3.0.7 on 2020-07-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('name', models.CharField(max_length=120, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی (محصول)',
                'verbose_name_plural': 'دسته بندی ها(محصول)',
            },
        ),
    ]
